### ISSUE TITLE
Not sure why a south plugin is publishing data to a broker

### ISSUE THREAD

**Issue by sudhirkshirsagar** [fledge-iot/fledge-south-mqtt#2]
It should be subscribing and ingesting into the gateway.

**Comment by praveen-garg** [comment]
Hi @sudhirkshirsagar 

> It should be subscribing and ingesting into the gateway.

Indeed! South plugin is a subscriber only.  

> Not sure why a south plugin is publishing data to a broker #2

No, South plugin is **not publishing** any data. Its objective (obvious design) is to subscribe the topic and ingest as published on the subscribed topic.

Please check README / give a try to plugin. Let us know if need other clarifications.
Hope this helps!

**Comment by sudhirkshirsagar** [comment]
When I saw the code yesterday, I saw a publisher. The code today is subscribing.

**Comment by praveen-garg** [comment]
> When I saw the code yesterday, I saw a publisher. The code today is subscribing.

Could you please point to the commit # of the code you saw yesterday? This repository has the subscriber code since its first commit.

**Comment by sudhirkshirsagar** [comment]
I tried to look for it but I can't see that. I was looking at it along with Dr. Steve Mylroie and he had the same comment.
